###############################
## synapter interface generics
setGeneric("isSynapterObjectOutOfDate", function(object, ...) standardGeneric("isSynapterObjectOutOfDate"))
setGeneric("inputFiles", function(object, ...) standardGeneric("inputFiles"))
setGeneric("loadSpectrumXmlFiles", function(object, ...) standardGeneric("loadSpectrumXmlFiles"))
setGeneric("loadFragmentCsvFiles", function(object, ...) standardGeneric("loadFragmentCsvFiles"))
setGeneric("getLog", function(object, ...) standardGeneric("getLog"))
setGeneric("mergePeptides", function(object, ...) standardGeneric("mergePeptides"))
setGeneric("modelRt", function(object, ...) standardGeneric("modelRt"))
setGeneric("findEMRTs", function(object, ...) standardGeneric("findEMRTs"))
setGeneric("searchGrid", function(object, ...) standardGeneric("searchGrid"))
setGeneric("getGrid", function(object, ...) standardGeneric("getGrid"))
setGeneric("getGridDetails", function(object, ...) standardGeneric("getGridDetails"))
setGeneric("getBestGridValue", function(object, ...) standardGeneric("getBestGridValue"))
setGeneric("getBestGridParams", function(object, ...) standardGeneric("getBestGridParams"))
setGeneric("setBestGridParams", function(object, ...) standardGeneric("setBestGridParams"))
setGeneric("setPepScoreFdr", function(object, ...) standardGeneric("setPepScoreFdr"))
setGeneric("getPepScoreFdr", function(object, ...) standardGeneric("getPepScoreFdr"))
setGeneric("setProtFpr", function(object, ...) standardGeneric("setProtFpr"))
setGeneric("getProtFpr", function(object, ...) standardGeneric("getProtFpr"))
setGeneric("setIdentPpmError", function(object, ...) standardGeneric("setIdentPpmError"))
setGeneric("getIdentPpmError", function(object, ...) standardGeneric("getIdentPpmError"))
setGeneric("setQuantPpmError", function(object, ...) standardGeneric("setQuantPpmError"))
setGeneric("getQuantPpmError", function(object, ...) standardGeneric("getQuantPpmError"))
setGeneric("setLowessSpan", function(object, ...) standardGeneric("setLowessSpan"))
setGeneric("getLowessSpan", function(object, ...) standardGeneric("getLowessSpan"))
setGeneric("setRtNsd", function(object, ...) standardGeneric("setRtNsd"))
setGeneric("getRtNsd", function(object, ...) standardGeneric("getRtNsd"))
setGeneric("setPpmError", function(object, ...) standardGeneric("setPpmError"))
setGeneric("getPpmError", function(object, ...) standardGeneric("getPpmError"))
setGeneric("setImDiff", function(object, ...) standardGeneric("setImDiff"))
setGeneric("getImDiff", function(object, ...) standardGeneric("getImDiff"))
setGeneric("getPpmErrorQs", function(object, ...) standardGeneric("getPpmErrorQs"))
setGeneric("getRtQs", function(object, ...) standardGeneric("getRtQs"))
setGeneric("getPepNumbers", function(object, ...) standardGeneric("getPepNumbers"))
setGeneric("setCrossMatchingPpmTolerance", function(object, ...) standardGeneric("setCrossMatchingPpmTolerance"))
setGeneric("getCrossMatchingPpmTolerance", function(object, ...) standardGeneric("getCrossMatchingPpmTolerance"))
setGeneric("showFdrStats", function(object, ...) standardGeneric("showFdrStats"))
setGeneric("filterPeptideLength", function(object, ...) standardGeneric("filterPeptideLength"))
setGeneric("filterUniqueDbPeptides", function(object, ...) standardGeneric("filterUniqueDbPeptides"))
setGeneric("filterUniqueQuantDbPeptides", function(object, ...) standardGeneric("filterUniqueQuantDbPeptides"))
setGeneric("filterUniqueIdentDbPeptides", function(object, ...) standardGeneric("filterUniqueIdentDbPeptides"))
setGeneric("filterQuantPepScore", function(object, ...) standardGeneric("filterQuantPepScore"))
setGeneric("filterIdentPepScore", function(object, ...) standardGeneric("filterIdentPepScore"))
setGeneric("filterQuantProtFpr", function(object, ...) standardGeneric("filterQuantProtFpr"))
setGeneric("filterIdentProtFpr", function(object, ...) standardGeneric("filterIdentProtFpr"))
setGeneric("filterIdentPpmError", function(object, ...) standardGeneric("filterIdentPpmError"))
setGeneric("filterQuantPpmError", function(object, ...) standardGeneric("filterQuantPpmError"))
setGeneric("filterFragments", function(object, ...) standardGeneric("filterFragments"))
setGeneric("filterUniqueMatches", function(object, ...) standardGeneric("filterUniqueMatches"))
setGeneric("filterNonUniqueMatches", function(object, ...) standardGeneric("filterNonUniqueMatches"))
setGeneric("plotPpmError", function(object, ...) standardGeneric("plotPpmError"))
setGeneric("plotRt", function(object, ...) standardGeneric("plotRt"))
setGeneric("plotPepScores", function(object, ...) standardGeneric("plotPepScores"))
setGeneric("plotFdr", function(object, ...) standardGeneric("plotFdr"))
setGeneric("plotFeatures", function(object, ...) standardGeneric("plotFeatures"))
setGeneric("plotCrossMatching", function(object, ...) standardGeneric("plotCrossMatching"))
setGeneric("plotCrossMatchingPerformance", function(object, ...) standardGeneric("plotCrossMatchingPerformance"))
setGeneric("plotCumulativeNumberOfFragments", function(object, ...) standardGeneric("plotCumulativeNumberOfFragments"))
setGeneric("getEMRTtable", function(object, ...) standardGeneric("getEMRTtable"))
setGeneric("plotEMRTtable", function(object, ...) standardGeneric("plotEMRTtable"))
setGeneric("performance", function(object, ...) standardGeneric("performance"))
setGeneric("performance2", function(object, ...) standardGeneric("performance2"))
setGeneric("plotRtDiffs", function(object, ...) standardGeneric("plotRtDiffs"))
setGeneric("plotGrid", function(object, ...) standardGeneric("plotGrid"))
setGeneric("crossMatching", function(object, ...) standardGeneric("crossMatching"))
setGeneric("writeIdentPeptides", function(object, ...) standardGeneric("writeIdentPeptides"))
setGeneric("writeQuantPeptides", function(object, ...) standardGeneric("writeQuantPeptides"))
setGeneric("writeMergedPeptides", function(object, ...) standardGeneric("writeMergedPeptides"))
setGeneric("writeMatchedEMRTs", function(object, ...) standardGeneric("writeMatchedEMRTs"))

###############################
## MasterPeptides
setGeneric("writeMasterPeptides", function(x, file, ...) standardGeneric("writeMasterPeptides"))
setGeneric("writeFragmentLibrary", function(x, file, ...) standardGeneric("writeFragmentLibrary"))

###############################
## MasterFdrResults
setGeneric("bestComb", function(object, ...) standardGeneric("bestComb"))
setGeneric("allComb", function(object, ...) standardGeneric("allComb"))
setGeneric("masterFdr", function(object, ...) standardGeneric("masterFdr"))
